practica 4/sesion 3 y 4/implementacion Ruby On Rails/config/routes.rb
Rails.application.routes.draw do
  resources :estado_propuesta
  resources :propuestas
  resources :tecnicos_controllers
  resources :tecnicos
  resources :mis_tecnicos
  resources :tipo_trabajos
  resources :clientes
  resources :trabajos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      namespace :api, defaults: { format: 'json' }  do
         namespace :v1 do
        	   resources :clientes, :tipo_trabajos, :tecnicos, :trabajos, :propuestas
              get '/propuestas/list/:id', to:'propuestas#list'
         end
      end

      root to: 'pages#home'
      get    '/login',   to: 'sessions#new'
      post   '/login',   to: 'sessions#create'
      get '/logout',  to: 'sessions#destroy'
      post '/logout',  to: 'sessions#destroy'
      delete '/logout',  to: 'sessions#destroy'
      get '/profile', to: 'clientes#profile'
      get '/trabajos/valorar/:id/:trabajo', to: 'trabajos#valorar'
      get  '/trabajos/valorado/:id/:trabajo', to: 'trabajos#valorar_bd'
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/models/tipo_trabajo.rb
class TipoTrabajo < ApplicationRecord
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/controllers/api/v1/tipo_trabajos_controller.rb
module Api
    module V1
        class TipoTrabajosController < ApplicationController
            skip_before_action :verify_authenticity_token

            def show
                @tipo_trabajo = TipoTrabajo.find_by(id: params[:id])
                if (@tipo_trabajo!=nil)
                    render json: @tipo_trabajo, status: :ok
            else
                render json: :nothing, status: :not_found
                end
            end

            def index
                    render json: TipoTrabajo.all, status: :ok
            end
        end
    end
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/controllers/tipo_trabajos_controller.rb
class TipoTrabajosController < ApplicationController
  before_action :set_tipo_trabajo, only: %i[ show edit update destroy ]

  # GET /tipo_trabajos or /tipo_trabajos.json
  def index
    @tipo_trabajos = TipoTrabajo.all
  end

  # GET /tipo_trabajos/1 or /tipo_trabajos/1.json
  def show
  end

  # GET /tipo_trabajos/new
  def new
    @tipo_trabajo = TipoTrabajo.new
  end

  # GET /tipo_trabajos/1/edit
  def edit
  end

  # POST /tipo_trabajos or /tipo_trabajos.json
  def create
    @tipo_trabajo = TipoTrabajo.new(tipo_trabajo_params)

    respond_to do |format|
      if @tipo_trabajo.save
        format.html { redirect_to @tipo_trabajo, notice: "Tipo trabajo was successfully created." }
        format.json { render :show, status: :created, location: @tipo_trabajo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tipo_trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_trabajos/1 or /tipo_trabajos/1.json
  def update
    respond_to do |format|
      if @tipo_trabajo.update(tipo_trabajo_params)
        format.html { redirect_to @tipo_trabajo, notice: "Tipo trabajo was successfully updated." }
        format.json { render :show, status: :ok, location: @tipo_trabajo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tipo_trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_trabajos/1 or /tipo_trabajos/1.json
  def destroy
    @tipo_trabajo.destroy
    respond_to do |format|
      format.html { redirect_to tipo_trabajos_url, notice: "Tipo trabajo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_trabajo
      @tipo_trabajo = TipoTrabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tipo_trabajo_params
      params.require(:tipo_trabajo).permit(:Tipo)
    end
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/helpers/tipo_trabajos_helper.rb
module TipoTrabajosHelper
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/tipo_trabajos/_form.html.erb
<%= form_with(model: tipo_trabajo) do |form| %>
  <% if tipo_trabajo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo_trabajo.errors.count, "error") %> prohibited this tipo_trabajo from being saved:</h2>

      <ul>
        <% tipo_trabajo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Tipo %>
    <%= form.text_field :Tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/tipo_trabajos/edit.html.erb
<h1>Editing Tipo Trabajo</h1>

<%= render 'form', tipo_trabajo: @tipo_trabajo %>

<%= link_to 'Show', @tipo_trabajo %> |
<%= link_to 'Back', tipo_trabajos_path %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/tipo_trabajos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipo Trabajos</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_trabajos.each do |tipo_trabajo| %>
      <tr>
        <td><%= tipo_trabajo.Tipo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Trabajo', new_tipo_trabajo_path %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/tipo_trabajos/new.html.erb
<h1>New Tipo Trabajo</h1>

<%= render 'form', tipo_trabajo: @tipo_trabajo %>

<%= link_to 'Back', tipo_trabajos_path %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/tipo_trabajos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @tipo_trabajo.Tipo %>
</p>

<%= link_to 'Edit', edit_tipo_trabajo_path(@tipo_trabajo) %> |
<%= link_to 'Back', tipo_trabajos_path %>