practica 4/sesion 3 y 4/implementacion Ruby On Rails/config/routes.rb
Rails.application.routes.draw do
  resources :estado_propuesta
  resources :propuestas
  resources :tecnicos_controllers
  resources :tecnicos
  resources :mis_tecnicos
  resources :tipo_trabajos
  resources :clientes
  resources :trabajos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      namespace :api, defaults: { format: 'json' }  do
         namespace :v1 do
        	   resources :clientes, :tipo_trabajos, :tecnicos, :trabajos, :propuestas
              get '/propuestas/list/:id', to:'propuestas#list'
         end
      end

      root to: 'pages#home'
      get    '/login',   to: 'sessions#new'
      post   '/login',   to: 'sessions#create'
      get '/logout',  to: 'sessions#destroy'
      post '/logout',  to: 'sessions#destroy'
      delete '/logout',  to: 'sessions#destroy'
      get '/profile', to: 'clientes#profile'
      get '/trabajos/valorar/:id/:trabajo', to: 'trabajos#valorar'
      get  '/trabajos/valorado/:id/:trabajo', to: 'trabajos#valorar_bd'
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/models/cliente.rb
class Cliente < ApplicationRecord
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/controllers/api/v1/clientes_controller.rb
module Api
    module V1
        class ClientesController < ApplicationController
            
skip_before_action :verify_authenticity_token

def show
      @cliente = Cliente.find_by(id: params[:id])
      if (@cliente!=nil)
        render json: @cliente, status: :ok
  else
       render json: :nothing, status: :not_found
    end
end

def index
        render json: Cliente.all, status: :ok
end
        end
    end
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/controllers/clientes_controller.rb
require 'digest'

class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes/1 or /clientes/1.json
  def show
    if session[:user_id] == nil
      redirect_back_or root_path
    end
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  def profile
    if session[:user_id] == nil
      redirect_back_or root_path
    else
      @cliente = Cliente.find_by(id: session[:user_id])
    end
  end

  # GET /clientes/1/edit
  def edit
    if session[:user_id] == nil
      redirect_back_or root_path
    end
  end

  # POST /clientes or /clientes.json
  def create
    create_params = cliente_params
    hash = Digest::SHA2.new
    clave = create_params[:contrasena]
    clave = hash.hexdigest(clave)
    create_params[:contrasena] = clave
    @cliente = Cliente.new(create_params)

    respond_to do |format|
      if @cliente.save
        session[:user_id] = @cliente.id
        format.html { redirect_to profile, notice: "El Cliente se ha creado correctamente" }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    rescue Exception => e
      if e.is_a? ActiveRecord::RecordNotUnique
        Rails.logger.warn(e)
        format.html { render :new, status: :unprocessable_entity, notice: "El Correo ya está en uso"  }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    if session[:user_id] == nil
      redirect_back_or root_path
    end

    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "El Cliente se ha actualizado correctamente" }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    if session[:user_id] == nil
      redirect_back_or root_path
    end

	 # Eliminar la sesion para destruir correctamente
	 session[:user_id] = nil

    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "El Cliente se ha borrado correctamente" }
      format.json { head :no_content }
    end

	 # Eliminar la sesion si se destruyó
	 session[:user_id] = nil
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellidos, :domicilio, :correo, :contrasena)
    end
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/helpers/clientes_helper.rb
module ClientesHelper
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
<div class = "formulario">
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, required: true%>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, required: true %>
  </div>

  <div class="field">
    <%= form.label :domicilio %>
    <%= form.text_field :domicilio, required: true %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.email_field :correo, required: true %>
  </div>

  <div class="field">
    <%= form.label :contrasena %>
    <%= form.password_field :contrasena, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/clientes/edit.html.erb
<div class="centrado">
    <div class="titulo">
        <h1>Editando Cliente</h1>
    </div>

    <div class="cuerpo_centro">
        <%= render 'form', cliente: @cliente %>
        <%= link_to 'Show', @cliente %>
    </div>
</div>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Domicilio</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.apellidos %></td>
        <td><%= cliente.domicilio %></td>
        <td><%= cliente.correo %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/clientes/new.html.erb
<p id="notice"><%= notice %></p>

<div class="centrado">
  <div class="titulo">
    <h1>Registro de clientes</h1>
  </div>

  <div class="cuerpo_centro">
      <%= render 'form', cliente: @cliente %>

  </div>
</div>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/clientes/profile.html.erb
<p id="notice"><%= notice %></p>

<div class="centrado">
  <div class="titulo">
    <h1>Perfil</h1>
  </div>

  <div class="cuerpo_centro">
      <p>
        <strong>Nombre:</strong>
        <%= @cliente.nombre %>
      </p>

      <p>
        <strong>Apellidos:</strong>
        <%= @cliente.apellidos %>
      </p>

      <p>
        <strong>Domicilio:</strong>
        <%= @cliente.domicilio %>
      </p>

      <p>
        <strong>Correo:</strong>
        <%= @cliente.correo %>
      </p>

    <%= link_to 'Edit', edit_cliente_path(@cliente) %>

  </div>
</div>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="centrado">
  <div class="titulo">
    <h1>Perfil</h1>
  </div>

  <div class="cuerpo_centro">
      <p>
        <strong>Nombre:</strong>
        <%= @cliente.nombre %>
      </p>

      <p>
        <strong>Apellidos:</strong>
        <%= @cliente.apellidos %>
      </p>

      <p>
        <strong>Domicilio:</strong>
        <%= @cliente.domicilio %>
      </p>

      <p>
        <strong>Correo:</strong>
        <%= @cliente.correo %>
      </p>

    <%= link_to 'Edit', edit_cliente_path(@cliente) %>

  </div>
</div>