practica 4/sesion 3 y 4/implementacion Ruby On Rails/config/routes.rb
Rails.application.routes.draw do
  resources :estado_propuesta
  resources :propuestas
  resources :tecnicos_controllers
  resources :tecnicos
  resources :mis_tecnicos
  resources :tipo_trabajos
  resources :clientes
  resources :trabajos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      namespace :api, defaults: { format: 'json' }  do
         namespace :v1 do
        	   resources :clientes, :tipo_trabajos, :tecnicos, :trabajos, :propuestas
              get '/propuestas/list/:id', to:'propuestas#list'
         end
      end

      root to: 'pages#home'
      get    '/login',   to: 'sessions#new'
      post   '/login',   to: 'sessions#create'
      get '/logout',  to: 'sessions#destroy'
      post '/logout',  to: 'sessions#destroy'
      delete '/logout',  to: 'sessions#destroy'
      get '/profile', to: 'clientes#profile'
      get '/trabajos/valorar/:id/:trabajo', to: 'trabajos#valorar'
      get  '/trabajos/valorado/:id/:trabajo', to: 'trabajos#valorar_bd'
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SOSEMADO Client View</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
  <nav>
        <div class="opcion_nav">
              <%= link_to image_tag("logo.png") + content_tag(:p, "SOSEMADO"), root_path, class:"logo" %>
        </div>
        <a class="menu-toggle" href="#" data-turbolinks="false">
                <span class="barra"></span>
                <span class="barra"></span>
                <span class="barra"></span>
        </a>

        <div class="menu">
          <ul>
            <% if session[:user_id] == nil %>
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Regístrate"), "/DS8/clientes/new" %></a></li>
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Iniciar sesión"), "/DS8/login" %></a></li>
            <% else %>
              <% cliente = Cliente.find_by(id: session[:user_id]) %>
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Mis trabajos"), trabajos_path %></li> 
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Crear trabajo"), new_trabajo_path %></a></li> 
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Logeado como #{cliente[:nombre]} #{cliente[:apellidos]}"), "#"  %></li> 
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Mi perfil"), "/DS8/profile " %></a></li>
              <li class="opcion_nav_right"><%= link_to content_tag(:p, "Cerrar sesión"), "/DS8/logout" %></a></li>    
            <% end %>
          </ul> 
        </div>
          
    </nav>  
    <%= javascript_pack_tag 'toggleButton' %>
    <%= yield %>
  </body>
</html>