practica 4/sesion 3 y 4/implementacion Ruby On Rails/config/routes.rb
Rails.application.routes.draw do
  resources :estado_propuesta
  resources :propuestas
  resources :tecnicos_controllers
  resources :tecnicos
  resources :mis_tecnicos
  resources :tipo_trabajos
  resources :clientes
  resources :trabajos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      namespace :api, defaults: { format: 'json' }  do
         namespace :v1 do
        	   resources :clientes, :tipo_trabajos, :tecnicos, :trabajos, :propuestas
              get '/propuestas/list/:id', to:'propuestas#list'
         end
      end

      root to: 'pages#home'
      get    '/login',   to: 'sessions#new'
      post   '/login',   to: 'sessions#create'
      get '/logout',  to: 'sessions#destroy'
      post '/logout',  to: 'sessions#destroy'
      delete '/logout',  to: 'sessions#destroy'
      get '/profile', to: 'clientes#profile'
      get '/trabajos/valorar/:id/:trabajo', to: 'trabajos#valorar'
      get  '/trabajos/valorado/:id/:trabajo', to: 'trabajos#valorar_bd'
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/models/trabajo.rb
class Trabajo < ApplicationRecord
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/controllers/api/v1/trabajos_controller.rb
module Api
    module V1
        class TrabajosController < ApplicationController
            
skip_before_action :verify_authenticity_token

def show
      @trabajo = Trabajo.find_by(id: params[:id])
      if (@trabajo!=nil)
        render json: @trabajo, status: :ok
  else
       render json: :nothing, status: :not_found
    end
end

def index
        render json: Trabajo.all, status: :ok
end

def update
 @trabajo = Trabajo.find(params[:id])

  if @trabajo.update(trabajo_params)
        render json: @trabajo, status: :ok
      else
        render json: @trabajo.errors, status: :unprocessable_entity
      end
end

def create
    @trabajo = Trabajo.new(trabajo_params)

      if @trabajo.save
        render json: @trabajo, status: :created
      else
        render json: @trabajo.errors, status: :unprocessable_entity
      end
end

def destroy
    @trabajo = Trabajo.find(params[:id])
    if @trabajo.destroy
      render json: :nothing, status: :ok
    else
      render json: :nothing, status: :unprocessable_entity
    end
end
private
def trabajo_params
      params.permit(:descripcion, :localizacion, :presupuesto, :tipotrabajo, :Id_tecnico);
end
        end
    end
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController
  before_action :set_trabajo, only: %i[ show edit update destroy ]
	# @@valoracion = 5
	# @@num_trabajos = 10
  # GET /trabajos or /trabajos.json
  def index
    if session[:user_id] == nil
      redirect_back_or root_path
    end
    @trabajos = Trabajo.where(Id_cliente: session[:user_id])
    #puts @trabajos[:descripcion]
  end

  # GET /trabajos/1 or /trabajos/1.json
  def show
    if session[:user_id] == nil
      redirect_back_or root_path
    end

	 comprobarAsignacionTecnico()
  end
  # GET /trabajos/new
  def new
    if session[:user_id] == nil
      redirect_back_or root_path
    end
    @trabajo = Trabajo.new
  end

  # GET /trabajos/1/edit
  def edit
    if session[:user_id] == nil
      redirect_back_or root_path
    end
  end

  # POST /trabajos or /trabajos.json
  def create
    if session[:user_id] == nil
      redirect_back_or root_path
    end

    create_params = trabajo_params
    create_params[:Id_cliente] = session[:user_id]
    @trabajo = Trabajo.new(create_params)

    respond_to do |format|
      if @trabajo.save
        format.html { redirect_to @trabajo, notice: "Trabajo correctamente añadido." }
        format.json { render :show, status: :created, location: @trabajo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end

      print create_params
	 proponer_trabajo(create_params[:presupuesto])

  end

  # PATCH/PUT /trabajos/1 or /trabajos/1.json
  def update
    if session[:user_id] == nil
      redirect_back_or root_path
    end
    respond_to do |format|
      if @trabajo.update(trabajo_params)
        format.html { redirect_to @trabajo, notice: "Trabajo correctamente actualizado." }
        format.json { render :show, status: :ok, location: @trabajo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  def valorar

  end

  def valorar_bd
    print params
    tecnico = Tecnico.find_by(id: params[:id])
    if (tecnico != nil)
      valor = params[:valoracion].to_i
      if (valor > 10)
        valor = 10
      elsif (valor < 0)
        valor = 0
      end

      if tecnico[:num_trabajos] > 1 
        valoracion = (tecnico[:valoracion] * (tecnico[:num_trabajos] - 1))/tecnico[:num_trabajos] + valor/tecnico[:num_trabajos]
      end

      consulta = "UPDATE tecnicos SET valoracion = #{valoracion} WHERE id = #{tecnico[:id]}"
      records_array = ActiveRecord::Base.connection.execute(consulta)

      print params[:trabajo]
      consulta = "UPDATE propuestas SET estado = 'TERMINADO' WHERE trabajo = #{params[:trabajo]} and tecnico= #{tecnico[:id]}"
      records_array = ActiveRecord::Base.connection.execute(consulta)
      redirect_back_or trabajos_path
    else
      redirect_back_or trabajos_path
    end
  end


  # DELETE /trabajos/1 or /trabajos/1.json
  def destroy
    if session[:user_id] == nil
      redirect_back_or root_path
    end
    @trabajo.destroy
    respond_to do |format|
      format.html { redirect_to trabajos_url, notice: "Trabajo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajo
      @trabajo = Trabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabajo_params
      params.require(:trabajo).permit(:descripcion, :localizacion, :presupuesto, :tipotrabajo, :Id_tecnico, :Id_cliente, :valoracion, :trabajoid)
    end

	 def proponer_trabajo(presupuesto)
    print "Proponiendo trabajo"

		  valoracion = 5
		 num_trabajos = 10
		 #
 records_array = []
 while records_array.size == 0 and valoracion > 0

			 seleccion = " SELECT * FROM tecnicos "
			  condiciones = " WHERE valoracion > #{valoracion} AND num_trabajos < #{num_trabajos} ";
			# condiciones = " WHERE valoracion > 5 AND num_trabajos < 10";
			 preferencia = " ORDER BY valoracion DESC, num_trabajos ASC "

			 consulta = seleccion + condiciones + preferencia;

			 records_array = ActiveRecord::Base.connection.execute(consulta)

			 records_array.each do |record|
			   consulta =
			 	  "INSERT INTO propuestas(trabajo, tecnico, presupuesto)
			 	  VALUES(#{@trabajo.id}, #{record[0]}, #{presupuesto})"

			   ActiveRecord::Base.connection.execute(consulta)

			 end

  valoracion = valoracion - 1
  num_trabajos = num_trabajos +1
 end
	 end

	 def comprobarAsignacionTecnico

		 # preparamos consulta para obtener propuestas de este trabajo que
		  # hayan sido aceptadas por los tecnicos y dispongan de un presupuesto
		 seleccion = "SELECT tecnico, presupuesto,id FROM propuestas"
		 condiciones = " WHERE trabajo = #{@trabajo.id} AND (estado ='CONFIRMADO' OR estado = 'CONFIRMADA')";
		 preferencia = " ORDER BY presupuesto ASC";

		 consulta = seleccion + condiciones + preferencia;
		 records_array = ActiveRecord::Base.connection.execute(consulta)

		 primero = []
		 records_array.each do |record|
			 primero = record
			 break
		 end

		 if (primero.length > 0)
      print primero
			 # actualizar este trabajo
			 @trabajo.Id_tecnico = primero[0]
			 @trabajo.presupuesto = primero[1]

			 @trabajo.save

      consulta = "UPDATE propuestas SET estado = 'ASIGNADO' WHERE id = #{primero[2]}"
      records_array = ActiveRecord::Base.connection.execute(consulta)

			 # params[:Id_tecnico] = @trabajo.Id_tecnico
			 # params[:presupuesto] = @trabajo.presupuesto
			 #
		 	#@trabajo.update(params)
		 else
			 print("No hay propuestas confirmadas todavia lo siento")
		 end
	 end
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/helpers/trabajos_helper.rb
module TrabajosHelper
end

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/trabajos/_form.html.erb
<%= form_with(model: trabajo) do |form| %>
  <% if trabajo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trabajo.errors.count, "error") %> prohibited this trabajo from being saved:</h2>

      <ul>
        <% trabajo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :localizacion %>
    <%= form.text_field :localizacion %>
  </div>

  <!-- Vamos a hacer un desplegable -->
  <div class="field">
	  <%= form.label :tipotrabajo %>
	  <%= form.collection_select :tipotrabajo, TipoTrabajo.all, :Tipo, :Tipo %>
  </div>

  <div class="field">
    <p>Presupuesto máximo</p>
    <%= form.text_field :presupuesto %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/trabajos/edit.html.erb
<div class="centrado">
    <div class="titulo">
        <h1>Editando Trabajo</h1>
    </div>
    <div class="cuerpo_centro">
        <%= render 'form', trabajo: @trabajo %>

        <%= link_to 'Show', @trabajo %> |
        <%= link_to 'Back', trabajos_path %>
    </div>
</div>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/trabajos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trabajos</h1>

<% if @trabajos != nil && @trabajos.size != 0 %>
<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th>Localizacion</th>
      <th>Presupuesto</th>
		<th>Tipo trabajo</th>

		<th colspan="3"> Acciones</th>

	 </tr>
  </thead>

  <tbody>
    <% @trabajos.each do |trabajo| %>
      <tr>
        <% propuestas = Propuestas.find_by(trabajo: trabajo.id, estado: "ASIGNADO") %>
        <% if  propuestas != nil %>
          <td><%= trabajo.descripcion %> - <a href="/DS8/trabajos/valorar/<%= propuestas.tecnico%>/<%= trabajo.id%>">VALORAR</a> </td>
        <% else %>
          <td><%= trabajo.descripcion %> </td>
        <% end %>
        
        <td><%= trabajo.localizacion %></td>
        <td>
			  <% if trabajo.presupuesto %>
			  		<%= trabajo.presupuesto %>
			  <% else %>
			  		No hay presupuesto todavía
			  <% end %>
		  </td>
		  <td><%= trabajo.tipotrabajo %></td>
        <td><%= link_to 'Mostrar', trabajo %></td>
        <td><%= link_to 'Editar', edit_trabajo_path(trabajo) %></td>
        <td><%= link_to 'Eliminar', trabajo, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h3>¡Sin registros!<h3>
<% end %>

<br>

<%= link_to 'Añadir un nuevo trabajo', new_trabajo_path %>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/trabajos/new.html.erb
<% if session[:user_id] == nil%>
    <%= redirect_back_or root_path %>
<% end %>

<div class="centrado">
    <div class="titulo">
        <h1>Describa su problema :)</h1>
    </div>
    <div class="cuerpo_centro">
       <%= render 'form', trabajo: @trabajo %>
        <%= link_to 'Back', trabajos_path %>
    </div>
</div>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/trabajos/show.html.erb
<h1 id="notice"><%= notice %></h1>



<div class="centrado">
  <div class="titulo">
    <h1>Trabajo</h1>
  </div>

  <div class="cuerpo_centro">
      <p>
        <strong>Descripcion:</strong>
        <%= @trabajo.descripcion %>
      </p>

      <p>
        <strong>Localizacion:</strong>
        <%= @trabajo.localizacion %>
      </p>

      <p>
        <strong>Presupuesto:</strong>
        <!-- Esto es ruby embebido, hay que usar porcentajes para cada linea -->
        <% if @trabajo.presupuesto %>
          <%= @trabajo.presupuesto %>
        <% else %>
          Aún no hay presupuesto asignado
        <% end %>
      </p>

      <p>
        <strong>Tipo de trabajo:</strong>
        <%= @trabajo.tipotrabajo%>
      </p>

      <%= link_to 'Edit', edit_trabajo_path(@trabajo) %> |
      <%= link_to 'Back', trabajos_path %>

  </div>
</div>

practica 4/sesion 3 y 4/implementacion Ruby On Rails/app/views/trabajos/valorar.html.erb
<% if session[:user_id] == nil%>
    <%= redirect_back_or root_path %>
<% end %>

<div class="centrado">
    <div class="titulo">
        <h1>Valore al técnico</h1>
    </div>
    <div class="cuerpo_centro">
       <form action="/DS8/trabajos/valorado/<%= params[:id]%>/<%= params[:trabajo]%>" method="GET">
        <label for="Valoracion">Valoración </label>
        <input type="number" name="valoracion">
        <label for="Trabajoid">ID. Trabajo </label>
        <input type="number" name="trabajoid" value="<%= params[:trabajo]%>" disabled>
        <button type="submit">Enviar valoración</button>
       </form>
        <%= link_to 'Back', trabajos_path %>
    </div>
</div>